### ISSUE TITLE
Tweet for the hackathon on improving registration.

### ISSUE THREAD

**Issue by dianaiusan** [coderefinery/coderefinery-twitter#42]
I was trying to find some suitable text for the tweet. Please check below a suggestion. Any ideas how this could be improved?

Registration how-to for big online workshops. Check the results of our brainstorming hackathon in the blog: https://coderefinery.org/blog/2022/05/04/improving-workshop-registration/. Have you attended any of our in-person or online workshops?

#coderefinery #carpentries #onlinelearning #workshop

**Comment by MatiasJJ** [comment]
We are improving the registration for big online workshops. Check the the blog about our brainstorming hackathon in: https://coderefinery.org/blog/2022/05/04/improving-workshop-registration/. 
Have you attended any of our in-person or online workshops?

#coderefinery #carpentries #onlinelearning #workshop

**Comment by bast** [comment]
Done in #43.
